lab2/Models/CalcModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace lab2.Models
{
    public class CalcModel
    {
        public int a { get; set; }
        public int b { get; set; }
        public string Operation { get; set; }
        public string Calculate()
        {
            return Operation switch
            {
                "+" => $"{a} + {b} = {a + b}",
                "-" => $"{a} - {b} = {a - b}",
                "*" => $"{a} * {b} = {a * b}",
                "/" => b == 0 ? "Can't devide by zero": $"{a} / {b} = {a / b}",
                _ => "Invalid input"
            };
        }
    }
    
}

lab2/Controllers/CalculateController.cs
using lab2.Models;
using Microsoft.AspNetCore.Mvc;
using System;


namespace lab2.Controllers
{
    public class CalculateController : Controller
    {

        public IActionResult Manual()
        {
            if (Request.Method == "POST")
            {
                var model = new CalcModel
                {
                    a = Convert.ToInt32(HttpContext.Request.Form["a"]),
                    Operation = HttpContext.Request.Form["operation"],
                    b = Convert.ToInt32(HttpContext.Request.Form["b"])
                };
                ViewBag.Result = model.Calculate();
                return View("Result");
            }

            return View("HtmlHelpers");
        }
        [HttpGet]
        [ActionName("ManualWithSeparateHandlers")]
        public IActionResult ManualWithSeparateHandlersGet()
        {
            return View("HtmlHelpers");
        }
        [HttpPost]
        [ActionName("ManualWithSeparateHandlers")]
        public IActionResult ManualWithSeparateHandlersPost()
        {
            var model = new CalcModel
            {
                a = Convert.ToInt32(HttpContext.Request.Form["a"]),
                Operation = HttpContext.Request.Form["operation"],
                b = Convert.ToInt32(HttpContext.Request.Form["b"])
            };
            ViewBag.Result = model.Calculate();
            return View("Result");
        }

        [HttpGet]
        public IActionResult ModelBindingInParameters()
        {
            return View("HtmlHelpers");
        }

        [HttpPost]
        public IActionResult ModelBindingInParameters(int a, string operation, int b)
        {
            if (ModelState.IsValid)
            {
                var model = new CalcModel
                {
                    a = a,
                    Operation = operation,
                    b = b
                };
                ViewBag.Result = model.Calculate();
            }
            else
            {
                ViewBag.Result = "Invalid input";
            }

            return View("Result");
        }

        [HttpGet]
        public IActionResult ModelBindingInSeparateModel()
        {
            return View("TagHelpers");
        }
        [HttpPost]
        public IActionResult ModelBindingInSeparateModel(CalcModel model)
        {
            ViewBag.Result = ModelState.IsValid
                ? model.Calculate()
                : "Invalid input";

            return View("Result");
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

lab2/Views/Calculate/HtmlHelpers.cshtml
@model lab2.Models.CalcModel
@{
    var action = ViewContext.RouteData.Values["Action"] as string;
    ViewBag.Title = action;
    var operation = new SelectList(new[] { "+", "-", "*", "/" });
    var controller = ViewContext.RouteData.Values["Controller"] as string;

}
<h1>@action</h1>
@using (Html.BeginForm(action, controller, FormMethod.Post))
{
    @Html.TextBox("a", "")
    <br />
    @Html.DropDownList("operation", operation)
    <br />
    @Html.TextBox("b", "")
    <br />
    <button type="submit">Submit</button>
}

lab2/Views/Calculate/Index.cshtml
@{
    ViewData["Title"] = "Home Page - Backend2";
}

<h1>Form parametrs parsing demo</h1>
<ul>
    <li><a asp-controller="Calculate" asp-action="Manual">Manual parsing in single action</a></li>
    <li><a asp-controller="Calculate" asp-action="ManualWithSeparateHandlers">Manual parsing in separate actions</a></li>
    <li><a asp-controller="Calculate" asp-action="ModelBindingInParameters">Model binding (parameters)</a></li>
    <li><a asp-controller="Calculate" asp-action="ModelBindingInSeparateModel">Model binding (separate model)</a></li>
</ul>

lab2/Views/Calculate/TagHelpers.cshtml
@model lab2.Models.CalcModel
@{
    var action = ViewContext.RouteData.Values["Action"] as string;
    ViewBag.Title = action;
    var operations = new SelectList(new[] { "+", "-", "*", "/" });
}
<h1>@action</h1>
<form asp-controller="Calculate" asp-action="@action">
    <input asp-for="a" /><br />
    <select asp-for="Operation" asp-items="operations"></select><br />
    <input asp-for="b" /><br />
    <button type="submit">Submit</button>
</form>

lab2/Views/Shared/Result.cshtml

@{
    ViewBag.Title = "Result - Backend2";
}
<h1>Result</h1>
<div class="result">@ViewBag.Result</div>

lab2/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html>
<head>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <title>@ViewBag.Title - Backend2</title>
</head>
<body>
    <header>
        <h2>Backend2</h2>
        <nav><a asp-controller="Calculate" asp-action="Index">Home</a></nav>
    </header>
    <main>
        @RenderBody()
    </main>
    <footer>
        <hr />
        © 2021 - Backend2
    </footer>
</body>
</html>